// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQm7ffd1eqQeuZYP5Iar31mos6sIi2Jjk',
    appId: '1:416865709429:web:16527dda0a73f1bf2ab73c',
    messagingSenderId: '416865709429',
    projectId: 'flutterideias',
    authDomain: 'flutterideias.firebaseapp.com',
    storageBucket: 'flutterideias.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxPMIalHLWf6EyfD6lq7YgjFTSI9M5NM',
    appId: '1:416865709429:android:5c6fd8035dcb50a92ab73c',
    messagingSenderId: '416865709429',
    projectId: 'flutterideias',
    storageBucket: 'flutterideias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTq_dg09bwAC77O0xa6PaCF_U-bCN4HY',
    appId: '1:416865709429:ios:093e500e54b298d72ab73c',
    messagingSenderId: '416865709429',
    projectId: 'flutterideias',
    storageBucket: 'flutterideias.firebasestorage.app',
    iosBundleId: 'com.example.batalhadeideias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTq_dg09bwAC77O0xa6PaCF_U-bCN4HY',
    appId: '1:416865709429:ios:093e500e54b298d72ab73c',
    messagingSenderId: '416865709429',
    projectId: 'flutterideias',
    storageBucket: 'flutterideias.firebasestorage.app',
    iosBundleId: 'com.example.batalhadeideias',
  );
}
